global using System.Collections.Immutable;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using UnoTicTacToe.DataContracts;
global using UnoTicTacToe.DataContracts.Serialization;
global using UnoTicTacToe.Models;
global using UnoTicTacToe.Presentation;
global using UnoTicTacToe.Services.Caching;
global using UnoTicTacToe.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
